export const fundingData = [
	{
		id: 1,
		image: "/images/tree.jpg",
		tagType: "/type.svg",
		category: "Education",
		title: "Plant a Tree Campaign",
		description: "Help us plant 1,000 trees in the community.",
		amountCollected: 10,
		totalAmount: 100,
		remainingDays: 4,
		owner: "0x124545656565656...",
	},
	{
		id: 2,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Health",
		title: "Clean Water Initiative",
		description: "Providing clean water to remote villages.",
		amountCollected: 50,
		totalAmount: 200,
		remainingDays: 10,
		owner: "0x7890123456789abc...",
	},
	{
		id: 3,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Education",
		title: "School Supplies for Kids",
		description: "Support the education of underprivileged children.",
		amountCollected: 20,
		totalAmount: 100,
		remainingDays: 5,
		owner: "0xaabbccddeeff0011...",
	},
	{
		id: 4,
		image: "/images/animal-shelter.jpg",
		tagType: "/type.svg",
		category: "Animal Welfare",
		title: "Build an Animal Shelter",
		description: "Help provide shelter to stray animals.",
		amountCollected: 75,
		totalAmount: 150,
		remainingDays: 12,
		owner: "0x1122334455667788...",
	},
	{
		id: 5,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Health",
		title: "Hospital Equipment Fund",
		description: "Raising funds for essential hospital equipment.",
		amountCollected: 60,
		totalAmount: 250,
		remainingDays: 8,
		owner: "0x9988776655443322...",
	},
	{
		id: 6,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Environment",
		title: "Solar Power for Villages",
		description: "Bringing sustainable energy to rural areas.",
		amountCollected: 35,
		totalAmount: 150,
		remainingDays: 6,
		owner: "0x5566778899001122...",
	},
	{
		id: 7,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Charity",
		title: "Support Local Orphanage",
		description: "Providing food and education to orphaned children.",
		amountCollected: 100,
		totalAmount: 300,
		remainingDays: 7,
		owner: "0x7766554433221100...",
	},
	{
		id: 8,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Education",
		title: "Tech Skills Training",
		description: "Empowering youth with tech skills for the future.",
		amountCollected: 90,
		totalAmount: 200,
		remainingDays: 3,
		owner: "0x1234567890abcdef...",
	},
	{
		id: 9,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Charity",
		title: "Food Relief for Families",
		description: "Delivering food supplies to families in need.",
		amountCollected: 30,
		totalAmount: 100,
		remainingDays: 2,
		owner: "0xabc123def4567890...",
	},
	{
		id: 10,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Community",
		title: "Community Center Construction",
		description: "Building a safe space for community activities.",
		amountCollected: 85,
		totalAmount: 200,
		remainingDays: 14,
		owner: "0xabcdef0123456789...",
	},
	{
		id: 11,
		image: "/images/green-initiative.jpg",
		tagType: "/type.svg",
		category: "Environment",
		title: "Green Energy Initiative",
		description: "Promoting clean energy for a sustainable future.",
		amountCollected: 45,
		totalAmount: 180,
		remainingDays: 9,
		owner: "0x112233aabbccddeeff...",
	},
	{
		id: 12,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Health",
		title: "Mental Health Awareness",
		description: "Supporting mental health services in communities.",
		amountCollected: 40,
		totalAmount: 120,
		remainingDays: 5,
		owner: "0x33445566778899aa...",
	},
	{
		id: 13,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Charity",
		title: "Housing for the Homeless",
		description: "Providing temporary shelters for the homeless.",
		amountCollected: 110,
		totalAmount: 250,
		remainingDays: 15,
		owner: "0x123abc456def789ghi...",
	},
	{
		id: 14,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Environment",
		title: "Wildlife Conservation",
		description: "Protecting endangered species in the wild.",
		amountCollected: 25,
		totalAmount: 150,
		remainingDays: 11,
		owner: "0xaabbccddeeff001122...",
	},
	{
		id: 15,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Education",
		title: "Scholarship Fund",
		description: "Helping students achieve their academic dreams.",
		amountCollected: 80,
		totalAmount: 200,
		remainingDays: 4,
		owner: "0x556677889900abcdef...",
	},
	{
		id: 16,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Health",
		title: "Medical Research Grant",
		description: "Funding innovative medical research.",
		amountCollected: 95,
		totalAmount: 300,
		remainingDays: 12,
		owner: "0x998877665544aabbcc...",
	},
	{
		id: 17,
		image: "/images/clean-water.jpg",
		tagType: "/type.svg",
		category: "Environment",
		title: "Forest Conservation Project",
		description: "Preserving forests and natural habitats.",
		amountCollected: 70,
		totalAmount: 200,
		remainingDays: 13,
		owner: "0x1234567890abcdeff...",
	},
	{
		id: 18,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Charity",
		title: "Women Empowerment",
		description: "Supporting women entrepreneurs with seed funding.",
		amountCollected: 55,
		totalAmount: 150,
		remainingDays: 8,
		owner: "0xabcdeff0123456789a...",
	},
	{
		id: 19,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Charity",
		title: "Disaster Relief Fund",
		description: "Providing immediate aid to disaster-affected regions.",
		amountCollected: 65,
		totalAmount: 220,
		remainingDays: 10,
		owner: "0xabcdef1122334455cc...",
	},
	{
		id: 20,
		image: "/images/school-supplies.jpg",
		tagType: "/type.svg",
		category: "Environment",
		title: "Clean Energy for All",
		description: "Making renewable energy accessible for everyone.",
		amountCollected: 90,
		totalAmount: 300,
		remainingDays: 7,
		owner: "0xabcdef66778899aabb...",
	},
];
